<?php

if (session_status() === PHP_SESSION_NONE) {
  session_start();
}

const ADMIN_EMAIL = 'admin@gmail.com';

//use hash.php for generated by password_hash('yourpassword', PASSWORD_DEFAULT)
const ADMIN_PASS_HASH = '$2y$10$3i4fln1UbS8F7YZImUb8OOsjWZnX30DCwFgNCJe0xzC2rAFJvb/VK'; 
// NOTE: If you want, I can regenerate hash if needed. This format is correct for PHP password_verify().

// session key per admin page area (events/partners/memberlist)
function admin_session_key(string $area): string {
  return "admin_authed_" . $area;
}

function admin_is_authed(string $area): bool {
  return !empty($_SESSION[admin_session_key($area)]);
}

function admin_login(string $area, string $email): void {
  $_SESSION[admin_session_key($area)] = $email;
}

function admin_logout(string $area): void {
  unset($_SESSION[admin_session_key($area)]);
}

function admin_current_email(string $area): string {
  return (string)($_SESSION[admin_session_key($area)] ?? '');
}

function admin_check_credentials(string $email, string $password): bool {
  $email = strtolower(trim($email));
  $password = (string)$password;

  if ($email === '' || $password === '') return false;
  if ($email !== strtolower(ADMIN_EMAIL)) return false;

  return password_verify($password, ADMIN_PASS_HASH);
}